"""add news models

Revision ID: 5e28f0bda1d5
Revises: 7770efb3ff2d
Create Date: 2026-01-14 21:41:33.225827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e28f0bda1d5'
down_revision: Union[str, Sequence[str], None] = '7770efb3ff2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_task_user_id'), 'news_task', ['user_id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RSS', 'TELEGRAM', name='sourcetype'), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_user_id'), 'source', ['user_id'], unique=False)
    op.create_table('news_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uix_source_external_id'),
    sa.UniqueConstraint('source_id', 'url', name='uix_source_url')
    )
    op.create_index(op.f('ix_news_item_processed'), 'news_item', ['processed'], unique=False)
    op.create_index(op.f('ix_news_item_source_id'), 'news_item', ['source_id'], unique=False)
    op.create_table('source_news_task',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('news_task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_task_id'], ['news_task.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'news_task_id')
    )
    op.add_column('user', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    op.drop_table('source_news_task')
    op.drop_index(op.f('ix_news_item_source_id'), table_name='news_item')
    op.drop_index(op.f('ix_news_item_processed'), table_name='news_item')
    op.drop_table('news_item')
    op.drop_index(op.f('ix_source_user_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_news_task_user_id'), table_name='news_task')
    op.drop_table('news_task')
    # ### end Alembic commands ###
