"""add news_item_news_task table and remove processing fields from news_item

Revision ID: ce6450c4f79e
Revises: 68edc75c762b
Create Date: 2026-02-04 20:43:13.710460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce6450c4f79e'
down_revision: Union[str, Sequence[str], None] = '68edc75c762b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item_news_task',
    sa.Column('news_item_id', sa.Integer(), nullable=False),
    sa.Column('news_task_id', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['news_item_id'], ['news_item.id'], ),
    sa.ForeignKeyConstraint(['news_task_id'], ['news_task.id'], ),
    sa.PrimaryKeyConstraint('news_item_id', 'news_task_id')
    )
    op.create_index(op.f('ix_news_item_news_task_processed'), 'news_item_news_task', ['processed'], unique=False)
    
    # Add timestamp columns with server defaults for existing rows
    op.add_column('news_item', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('news_item', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # Remove processing fields
    op.drop_index(op.f('ix_news_item_processed'), table_name='news_item')
    op.drop_column('news_item', 'processed_at')
    op.drop_column('news_item', 'ai_response')
    op.drop_column('news_item', 'result')
    op.drop_column('news_item', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_item', sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('news_item', sa.Column('result', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('news_item', sa.Column('ai_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('news_item', sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_news_item_processed'), 'news_item', ['processed'], unique=False)
    op.drop_column('news_item', 'updated_at')
    op.drop_column('news_item', 'created_at')
    op.drop_index(op.f('ix_news_item_news_task_processed'), table_name='news_item_news_task')
    op.drop_table('news_item_news_task')
    # ### end Alembic commands ###
